package com.dlts.hrms.entity;

import java.util.Date;

public class SysUser {

	private String id;private String companyId;private String officeId;private String userName;private String password;private String no;private String name;private String email;private String phone;private String mobile;private String userType;private String photo;private String loginIp;private Date loginDate;private String loginFlag;private String createBy;private Date createDate;private String updateBy;private Date updateDate;private String remarks;private String delFlag;public String getId(){return this.id;}public void setId(String id){this.id=id;}public String getCompanyId(){return this.companyId;}public void setCompanyId(String companyId){this.companyId=companyId;}public String getOfficeId(){return this.officeId;}public void setOfficeId(String officeId){this.officeId=officeId;}public String getUserName(){return this.userName;}public void setUserName(String userName){this.userName=userName;}public String getPassword(){return this.password;}public void setPassword(String password){this.password=password;}public String getNo(){return this.no;}public void setNo(String no){this.no=no;}public String getName(){return this.name;}public void setName(String name){this.name=name;}public String getEmail(){return this.email;}public void setEmail(String email){this.email=email;}public String getPhone(){return this.phone;}public void setPhone(String phone){this.phone=phone;}public String getMobile(){return this.mobile;}public void setMobile(String mobile){this.mobile=mobile;}public String getUserType(){return this.userType;}public void setUserType(String userType){this.userType=userType;}public String getPhoto(){return this.photo;}public void setPhoto(String photo){this.photo=photo;}public String getLoginIp(){return this.loginIp;}public void setLoginIp(String loginIp){this.loginIp=loginIp;}public Date getLoginDate(){return this.loginDate;}public void setLoginDate(Date loginDate){this.loginDate=loginDate;}public String getLoginFlag(){return this.loginFlag;}public void setLoginFlag(String loginFlag){this.loginFlag=loginFlag;}public String getCreateBy(){return this.createBy;}public void setCreateBy(String createBy){this.createBy=createBy;}public Date getCreateDate(){return this.createDate;}public void setCreateDate(Date createDate){this.createDate=createDate;}public String getUpdateBy(){return this.updateBy;}public void setUpdateBy(String updateBy){this.updateBy=updateBy;}public Date getUpdateDate(){return this.updateDate;}public void setUpdateDate(Date updateDate){this.updateDate=updateDate;}public String getRemarks(){return this.remarks;}public void setRemarks(String remarks){this.remarks=remarks;}public String getDelFlag(){return this.delFlag;}public void setDelFlag(String delFlag){this.delFlag=delFlag;}

}
