package com.dlts.hrms.entity;

import java.util.Date;

public class SysUser {

	private String id;private String companyId;private String departmentId;private String username;private String password;private String code;private String name;private String email;private String phone;private String mobile;private String userType;private String photo;private String loginIp;private Date loginDate;private String loginFlag;private String createUserId;private Date createTime;private String updateUserId;private Date updateTime;private String remarks;public String getId(){return this.id;}public void setId(String id){this.id=id;}public String getCompanyId(){return this.companyId;}public void setCompanyId(String companyId){this.companyId=companyId;}public String getDepartmentId(){return this.departmentId;}public void setDepartmentId(String departmentId){this.departmentId=departmentId;}public String getUsername(){return this.username;}public void setUsername(String username){this.username=username;}public String getPassword(){return this.password;}public void setPassword(String password){this.password=password;}public String getCode(){return this.code;}public void setCode(String code){this.code=code;}public String getName(){return this.name;}public void setName(String name){this.name=name;}public String getEmail(){return this.email;}public void setEmail(String email){this.email=email;}public String getPhone(){return this.phone;}public void setPhone(String phone){this.phone=phone;}public String getMobile(){return this.mobile;}public void setMobile(String mobile){this.mobile=mobile;}public String getUserType(){return this.userType;}public void setUserType(String userType){this.userType=userType;}public String getPhoto(){return this.photo;}public void setPhoto(String photo){this.photo=photo;}public String getLoginIp(){return this.loginIp;}public void setLoginIp(String loginIp){this.loginIp=loginIp;}public Date getLoginDate(){return this.loginDate;}public void setLoginDate(Date loginDate){this.loginDate=loginDate;}public String getLoginFlag(){return this.loginFlag;}public void setLoginFlag(String loginFlag){this.loginFlag=loginFlag;}public String getCreateUserId(){return this.createUserId;}public void setCreateUserId(String createUserId){this.createUserId=createUserId;}public Date getCreateTime(){return this.createTime;}public void setCreateTime(Date createTime){this.createTime=createTime;}public String getUpdateUserId(){return this.updateUserId;}public void setUpdateUserId(String updateUserId){this.updateUserId=updateUserId;}public Date getUpdateTime(){return this.updateTime;}public void setUpdateTime(Date updateTime){this.updateTime=updateTime;}public String getRemarks(){return this.remarks;}public void setRemarks(String remarks){this.remarks=remarks;}

}
